//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArduinoToBluetooth {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArduinoToBluetooth.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arduino Port.
        /// </summary>
        internal static string arduinoPort {
            get {
                return ResourceManager.GetString("arduinoPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth Port.
        /// </summary>
        internal static string bluetoothPort {
            get {
                return ResourceManager.GetString("bluetoothPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear after sending.
        /// </summary>
        internal static string clearAfterSending {
            get {
                return ResourceManager.GetString("clearAfterSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to start.
        /// </summary>
        internal static string clickToStart {
            get {
                return ResourceManager.GetString("clickToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to stop.
        /// </summary>
        internal static string clickToStop {
            get {
                return ResourceManager.GetString("clickToStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened with Arduino&apos;s port: .
        /// </summary>
        internal static string errorArduino {
            get {
                return ResourceManager.GetString("errorArduino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened with the Bluetooth port: .
        /// </summary>
        internal static string errorBluetooth {
            get {
                return ResourceManager.GetString("errorBluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while creating Arduino&apos;s port: .
        /// </summary>
        internal static string errorCreatingArduino {
            get {
                return ResourceManager.GetString("errorCreatingArduino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while creating the Bluetooth port: .
        /// </summary>
        internal static string errorCreatingBluetooth {
            get {
                return ResourceManager.GetString("errorCreatingBluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while opening Arduino&apos;s port: .
        /// </summary>
        internal static string errorOpeningArduino {
            get {
                return ResourceManager.GetString("errorOpeningArduino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while opening the Bluetooth port: .
        /// </summary>
        internal static string errorOpeningBluetooth {
            get {
                return ResourceManager.GetString("errorOpeningBluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while sending data to Arduino&apos;s port:.
        /// </summary>
        internal static string errorSendingArduino {
            get {
                return ResourceManager.GetString("errorSendingArduino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while sending data to the Bluetooth port: .
        /// </summary>
        internal static string errorSendingBluetooth {
            get {
                return ResourceManager.GetString("errorSendingBluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid speed for Arduino&apos;s port! :(.
        /// </summary>
        internal static string invalidArduinoBaud {
            get {
                return ResourceManager.GetString("invalidArduinoBaud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Arduino port! :(.
        /// </summary>
        internal static string invalidArduinoPort {
            get {
                return ResourceManager.GetString("invalidArduinoPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid speed for the Bluetooth port! :(.
        /// </summary>
        internal static string invalidBluetoothBaud {
            get {
                return ResourceManager.GetString("invalidBluetoothBaud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Bluetooth port! :(.
        /// </summary>
        internal static string invalidBluetoothPort {
            get {
                return ResourceManager.GetString("invalidBluetoothPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line break.
        /// </summary>
        internal static string lineBreak {
            get {
                return ResourceManager.GetString("lineBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, wait....
        /// </summary>
        internal static string pleaseWait {
            get {
                return ResourceManager.GetString("pleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received bytes: .
        /// </summary>
        internal static string receivedBytes {
            get {
                return ResourceManager.GetString("receivedBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed (bps).
        /// </summary>
        internal static string speedBps {
            get {
                return ResourceManager.GetString("speedBps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
    }
}
